# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11d6jmklOF9fbK1HzhyUDu6UfkTSM3Aru
"""

!pip install ultralytics

from ultralytics import YOLO

# Load a model
model = YOLO("yolo11n.pt")

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/Intenship/Data/data.yaml",  # path to dataset YAML
    epochs=20,  # number of training epochs
    imgsz=640,  # training image size
    device=0,  # device to run on, i.e. device=0 or device=0,1,2,3 or device=cpu
)

from ultralytics import YOLO

# Load a model
model = YOLO("runs/detect/train/weights/best.pt")

# Perform object detection on an image
results = model("/content/drive/MyDrive/Intenship/Data/test/images/meningioma_1146_jpg.rf.592064ff6852418fe428a228a7c14458.jpg", save=True)
results[0].show()

# Load a model
model = YOLO("runs/detect/train/weights/best.pt")

# Perform object detection on an image
results = model("/content/drive/MyDrive/Intenship/Data/test images", save=True)

from ultralytics import YOLO

# Load a model
model = YOLO("runs/detect/train/weights/best.pt")  # pretrained YOLO11n model

# Run batched inference on a list of images
results = model("/content/drive/MyDrive/Intenship/Data/test images/meningioma_506_jpg.rf.5bf59f100f70b99b8b4568547fb1f4ca.jpg")  # return a list of Results objects

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    print(boxes)

from ultralytics import YOLO
from ultralytics import SAM

# Load the YOLO model
yolo_model = YOLO("runs/detect/train/weights/best.pt")  # pretrained YOLO model

# Run batched inference on a list of images
results = yolo_model("/content/drive/MyDrive/Intenship/Data/test images/meningioma_506_jpg.rf.5bf59f100f70b99b8b4568547fb1f4ca.jpg")  # return a list of Results objects

# Load the SAM model
sam_model = SAM("sam2_b.pt")

for result in results:
     class_ids = result.boxes.cls.int().tolist()  # noqa
     if len(class_ids):
         boxes = result.boxes.xyxy  # Boxes object for bbox outputs
         sam_results = sam_model(result.orig_img, bboxes=boxes, verbose=False, save=True, device=0)

